// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oficina.Infraestrutura.Persistencia;

#nullable disable

namespace Oficina.Infraestrutura.Migrations
{
    [DbContext(typeof(OficinaDbContext))]
    [Migration("20260914125322_HistoricoStatusEUnidade")]
    partial class HistoricoStatusEUnidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oficina.Dominio.Auth.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("perfil");

                    b.Property<bool>("PrecisaTrocarSenha")
                        .HasColumnType("boolean")
                        .HasColumnName("precisa_trocar_senha");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuario", "auth");
                });

            modelBuilder.Entity("Oficina.Dominio.Catalogo.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_base");

                    b.Property<int>("TempoEstimadoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_estimado_minutos");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("servico", "catalogo");
                });

            modelBuilder.Entity("Oficina.Dominio.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("cliente", "clientes");
                });

            modelBuilder.Entity("Oficina.Dominio.Clientes.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("modelo");

                    b.Property<Guid>("cliente_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("cliente_id");

                    b.ToTable("veiculo", "clientes");
                });

            modelBuilder.Entity("Oficina.Dominio.Estoque.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("motivo");

                    b.Property<Guid?>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("peca_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("peca_id", "CriadoEm")
                        .HasDatabaseName("ix_movimentacao_peca_data");

                    b.ToTable("movimentacao", "estoque", t =>
                        {
                            t.HasCheckConstraint("ck_movimentacao_quantidade_positiva", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("Oficina.Dominio.Estoque.Peca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("SaldoAtual")
                        .HasColumnType("integer")
                        .HasColumnName("saldo_atual");

                    b.HasKey("Id");

                    b.ToTable("peca", "estoque");
                });

            modelBuilder.Entity("Oficina.Dominio.OrdensServico.HistoricoStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("DuracaoSegundos")
                        .HasColumnType("bigint")
                        .HasColumnName("duracao_segundos");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("StatusAnterior")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status_anterior");

                    b.Property<string>("StatusNovo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status_novo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("ordem_servico_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatusAnterior", "OcorridoEm")
                        .HasDatabaseName("ix_historico_status_data");

                    b.HasIndex("ordem_servico_id", "OcorridoEm")
                        .HasDatabaseName("ix_historico_os");

                    b.ToTable("historico_status", "os");
                });

            modelBuilder.Entity("Oficina.Dominio.OrdensServico.ItemPeca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PecaId")
                        .HasColumnType("uuid")
                        .HasColumnName("peca_id");

                    b.Property<string>("PecaNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("peca_nome");

                    b.Property<decimal>("PrecoSnapshot")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_snapshot");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("ordem_servico_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ordem_servico_id");

                    b.ToTable("item_peca", "os", t =>
                        {
                            t.HasCheckConstraint("ck_item_peca_preco_nao_negativo", "preco_snapshot >= 0");

                            t.HasCheckConstraint("ck_item_peca_quantidade_positiva", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("Oficina.Dominio.OrdensServico.ItemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("PrecoSnapshot")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_snapshot");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<string>("ServicoNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("servico_nome");

                    b.Property<Guid>("ordem_servico_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ordem_servico_id");

                    b.ToTable("item_servico", "os", t =>
                        {
                            t.HasCheckConstraint("ck_item_servico_preco_nao_negativo", "preco_snapshot >= 0");

                            t.HasCheckConstraint("ck_item_servico_quantidade_positiva", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("Oficina.Dominio.OrdensServico.OrdemDeServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTimeOffset?>("DiagnosticadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("diagnosticada_em");

                    b.Property<DateTimeOffset?>("EntregueEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entregue_em");

                    b.Property<DateTimeOffset?>("EnviadaAprovacaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviada_aprovacao_em");

                    b.Property<DateTimeOffset?>("FinalizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalizada_em");

                    b.Property<DateTimeOffset?>("IniciadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciada_em");

                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Numero"));

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<DateTimeOffset?>("OrcamentoAprovadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("orcamento_aprovado_em");

                    b.Property<DateTimeOffset?>("OrcamentoRejeitadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("orcamento_rejeitado_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasDefaultValue("matriz")
                        .HasColumnName("unidade");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("Unidade")
                        .HasDatabaseName("ix_ordem_servico_unidade");

                    b.HasIndex("Status", "CriadaEm")
                        .HasDatabaseName("ix_ordem_servico_status_data");

                    b.ToTable("ordem_servico", "os");
                });

            modelBuilder.Entity("Oficina.Dominio.Clientes.Cliente", b =>
                {
                    b.OwnsOne("Oficina.Dominio.Clientes.Documento", "Documento", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("tipo_pessoa");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("documento");

                            b1.HasKey("ClienteId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("cliente", "clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("Oficina.Dominio.Clientes.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("email");

                            b1.HasKey("ClienteId");

                            b1.ToTable("cliente", "clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("Oficina.Dominio.Clientes.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("telefone");

                            b1.HasKey("ClienteId");

                            b1.ToTable("cliente", "clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Documento")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("Oficina.Dominio.Clientes.Veiculo", b =>
                {
                    b.HasOne("Oficina.Dominio.Clientes.Cliente", null)
                        .WithMany("Veiculos")
                        .HasForeignKey("cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Oficina.Dominio.Clientes.Placa", "Placa", b1 =>
                        {
                            b1.Property<Guid>("VeiculoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("placa");

                            b1.HasKey("VeiculoId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("veiculo", "clientes");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoId");
                        });

                    b.Navigation("Placa")
                        .IsRequired();
                });

            modelBuilder.Entity("Oficina.Dominio.Estoque.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Oficina.Dominio.Estoque.Peca", null)
                        .WithMany("Movimentacoes")
                        .HasForeignKey("peca_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oficina.Dominio.Estoque.Peca", b =>
                {
                    b.OwnsOne("Oficina.Dominio.Estoque.Sku", "Sku", b1 =>
                        {
                            b1.Property<Guid>("PecaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("sku");

                            b1.HasKey("PecaId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("peca", "estoque");

                            b1.WithOwner()
                                .HasForeignKey("PecaId");
                        });

                    b.Navigation("Sku")
                        .IsRequired();
                });

            modelBuilder.Entity("Oficina.Dominio.OrdensServico.HistoricoStatus", b =>
                {
                    b.HasOne("Oficina.Dominio.OrdensServico.OrdemDeServico", null)
                        .WithMany("Historico")
                        .HasForeignKey("ordem_servico_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oficina.Dominio.OrdensServico.ItemPeca", b =>
                {
                    b.HasOne("Oficina.Dominio.OrdensServico.OrdemDeServico", null)
                        .WithMany("ItensPeca")
                        .HasForeignKey("ordem_servico_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oficina.Dominio.OrdensServico.ItemServico", b =>
                {
                    b.HasOne("Oficina.Dominio.OrdensServico.OrdemDeServico", null)
                        .WithMany("ItensServico")
                        .HasForeignKey("ordem_servico_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oficina.Dominio.Clientes.Cliente", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("Oficina.Dominio.Estoque.Peca", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Oficina.Dominio.OrdensServico.OrdemDeServico", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("ItensPeca");

                    b.Navigation("ItensServico");
                });
#pragma warning restore 612, 618
        }
    }
}
